import { Job } from '../types';

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-sa-1',
    title: 'Heavy Truck Driver (Trailer)',
    category: 'Driving',
    location: 'Riyadh',
    description: 'Looking for experienced heavy truck drivers for long-distance transport between Riyadh, Dammam, and Jeddah. Must have valid KSA heavy driving license.',
    requirements: 'Valid Saudi Heavy License, 3+ years experience, transferable Iqama, ability to speak basic Arabic or English.',
    salary: '3,500 - 4,500 SAR / month + trip allowance',
    whatsapp_number: '966501234567',
    email: 'logistics.jobs@ksa-today.com',
    phone: '+966501234567',
    company_name: 'Al-Majdouie Logistics',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
  },
  {
    id: 'job-sa-2',
    title: 'Site Safety Inspector - Construction',
    category: 'Construction',
    location: 'Jeddah',
    description: 'Urgent requirement for Site Safety Inspectors for ongoing high-rise project in Jeddah Corniche. NEBOSH certification required.',
    requirements: 'NEBOSH IGC certified, 2+ years on Saudi construction sites, knowledge of OHSAS standards.',
    salary: '6,000 - 8,000 SAR / month',
    whatsapp_number: '966559876543',
    email: 'careers@binladen-group.com',
    phone: '+966559876543',
    company_name: 'Red Sea Builders Co.',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
  },
  {
    id: 'job-sa-3',
    title: 'Executive Assistant & Office Admin',
    category: 'Admin/Office',
    location: 'Riyadh',
    description: 'Leading technology company in King Abdullah Financial District (KAFD) is hiring an Executive Admin Assistant for office operations and calendar management.',
    requirements: 'Bilingual (Arabic & English), proficiency in MS Office & Google Workspace, 2+ years administrative experience in Saudi Arabia.',
    salary: '5,500 - 7,000 SAR / month',
    whatsapp_number: '966541122334',
    email: 'hr@kafd-tech.sa',
    phone: '+966541122334',
    company_name: 'KAFD Tech Solutions',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // 12 hours ago
  },
  {
    id: 'job-sa-4',
    title: 'Restaurant Cashier & Customer Service',
    category: 'Hospitality',
    location: 'Khobar',
    description: 'Fast-growing casual dining chain in Al Khobar is seeking polite cashiers to handle POS transactions and assist guests.',
    requirements: 'Positive attitude, basic numerical skills, customer-oriented, experience with Foodics POS is a plus.',
    salary: '3,000 - 3,800 SAR / month + free meal',
    whatsapp_number: '966567788990',
    email: 'jobs@khobar-dine.com',
    phone: '+966567788990',
    company_name: 'Eastern Hospitality Group',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
  },
  {
    id: 'job-sa-5',
    title: 'Food Delivery Driver (Motorcycle / Car)',
    category: 'Delivery',
    location: 'Mecca',
    description: 'Earn daily with flexible shifts delivering food across Mecca. Company motorcycle or car can be provided for qualified candidates.',
    requirements: 'Valid Saudi driver or bike license, smartphone with GPS capability, transferable Iqama.',
    salary: '3,500 - 5,000 SAR / month (Base + Commission)',
    whatsapp_number: '966533445566',
    email: 'makkah.delivery@hunger-ksa.com',
    phone: '+966533445566',
    company_name: 'FastExpress KSA',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
  },
  {
    id: 'job-sa-6',
    title: 'Full Stack Web Developer (React & Node)',
    category: 'IT',
    location: 'Riyadh',
    description: 'Join a premier Fintech startup in Riyadh developing next-generation payment solutions. Remote / Hybrid options available.',
    requirements: 'Strong experience with React, TypeScript, Node.js, and Postgres/Supabase. 3+ years software development experience.',
    salary: '12,000 - 18,000 SAR / month',
    whatsapp_number: '966512233445',
    email: 'tech-jobs@saudipay.sa',
    phone: '+966512233445',
    company_name: 'SaudiPay Tech',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
  {
    id: 'job-sa-7',
    title: 'Security Officer - Mall & Commercial Tower',
    category: 'Security',
    location: 'Dammam',
    description: 'Security guards needed for commercial center in Dammam. Shift-based work with health insurance and social security.',
    requirements: 'Saudi National or valid Iqama holder, clean criminal background check, physical fitness.',
    salary: '3,200 - 4,000 SAR / month',
    whatsapp_number: '966598877665',
    email: 'security@dammam-mall.com',
    phone: '+966598877665',
    company_name: 'Shield Security KSA',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: 'job-sa-8',
    title: 'Registered General Nurse (Hospital)',
    category: 'Healthcare',
    location: 'Medina',
    description: 'Private hospital in Medina is hiring qualified staff nurses for outpatient and emergency departments.',
    requirements: 'Bachelor Degree in Nursing, valid SCFHS (Saudi Commission for Health Specialties) license, minimum 2 years hospital experience.',
    salary: '7,000 - 9,500 SAR / month + housing allowance',
    whatsapp_number: '966544332211',
    email: 'recruitment@medina-hospital.med.sa',
    phone: '+966544332211',
    company_name: 'Al-Madinah Specialist Hospital',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
  },
  {
    id: 'job-sa-9',
    title: 'Retail Store Sales Associate',
    category: 'Retail',
    location: 'Taif',
    description: 'Seeking energetic sales representatives for luxury perfume and fashion retail outlet in Taif City Center.',
    requirements: 'Excellent communication skills, neat appearance, previous retail sales experience preferred.',
    salary: '3,500 - 4,200 SAR / month + sales target bonuses',
    whatsapp_number: '966556677889',
    email: 'sales@taif-fashion.com',
    phone: '+966559988776',
    company_name: 'Al-Othaim Retail',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: 'job-sa-10',
    title: 'Commercial Cleaning Supervisor',
    category: 'Cleaning',
    location: 'Jubail',
    description: 'Supervisor needed to manage cleaning crews across industrial facility offices in Jubail Industrial City.',
    requirements: 'Minimum 2 years experience in facility maintenance or industrial cleaning supervision.',
    salary: '3,800 - 4,500 SAR / month + accommodation',
    whatsapp_number: '966509988776',
    email: 'cleaning@jubail-services.com',
    phone: '+966509988776',
    company_name: 'Jubail Maintenance Corp',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
  },
  {
    id: 'job-sa-11',
    title: 'Hotel Front Desk Agent',
    category: 'Hospitality',
    location: 'Abha',
    description: '4-Star Resort in Abha is hiring Front Desk Agents for guest check-in, reservations, and customer support.',
    requirements: 'Fluent Arabic and English speaking, computer proficiency, hospitality diploma or degree.',
    salary: '4,000 - 5,000 SAR / month',
    whatsapp_number: '966511223344',
    email: 'hr@abha-resorts.sa',
    phone: '+966511223344',
    company_name: 'Asir Tourism Resorts',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
  },
  {
    id: 'job-sa-12',
    title: 'Warehouse Operations Helper',
    category: 'Other',
    location: 'Yanbu',
    description: 'Helpers required for loading, sorting, and inventory tagging in logistic warehouse in Yanbu Port area.',
    requirements: 'Physically fit, reliable, transferable Iqama.',
    salary: '2,800 - 3,400 SAR / month + overtime',
    whatsapp_number: '966522334455',
    email: 'warehouse@yanbu-logistics.com',
    phone: '+966522334455',
    company_name: 'Yanbu Port Services',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
  },
];
